from pydantic import BaseModel, Field


class SymptomSnapshot(BaseModel):
    """Extracted ACL intake symptoms collected during conversation."""

    mechanism: str | None = None
    heard_pop: bool | None = None
    swelling_level: str | None = None
    pain_level: int | None = Field(default=None, ge=0, le=10)
    instability: bool | None = None
    weight_bearing: str | None = None
    prior_acl_history: bool | None = None
    surgery_status: str | None = None
    additional_notes: str | None = None


class IntakeTurnResult(BaseModel):
    """Structured result from processing one intake message."""

    assistant_message: str
    updated_symptoms: SymptomSnapshot
    is_ready_for_assessment: bool
    missing_fields: list[str]


class AclAssessmentResult(BaseModel):
    """Structured ACL assessment generated by the AI."""

    likely_grade: str = Field(pattern="^(1|2|3|uncertain)$")
    confidence: float = Field(ge=0.0, le=1.0)
    reasoning: str
    urgency: str = Field(pattern="^(immediate|soon|routine)$")


class CreateIntakeSessionRequest(BaseModel):
    """Optional payload when starting a new intake session."""

    injury_type: str = "acl"


class SendIntakeMessageRequest(BaseModel):
    """User message within an active intake session."""

    content: str = Field(min_length=1)


class IntakeMessageResponse(BaseModel):
    """Single intake conversation message."""

    id: int
    role: str
    content: str
    created_at: str


class CarePlanResponse(BaseModel):
    """Interim care plan returned after assessment."""

    summary: str
    exercises: list[dict]
    avoid_activities: list[str]
    warning_signs: list[str]
    recovery_timeline_weeks: str


class AclAssessmentResponse(BaseModel):
    """ACL assessment details."""

    likely_grade: str
    confidence: float
    reasoning: str
    urgency: str
    recommend_doctor: bool
    created_at: str


class IntakeSessionResponse(BaseModel):
    """Full intake session state."""

    id: int
    injury_type: str
    status: str
    created_at: str
    messages: list[IntakeMessageResponse]
    symptoms: SymptomSnapshot | None
    assessment: AclAssessmentResponse | None
    care_plan: CarePlanResponse | None
    is_ready_for_assessment: bool


class SendIntakeMessageResponse(BaseModel):
    """Response after sending a message in an intake session."""

    assistant_message: str
    symptoms: SymptomSnapshot
    is_ready_for_assessment: bool
    missing_fields: list[str]


class AssessIntakeSessionResponse(BaseModel):
    """Response after finalizing an intake assessment."""

    session_id: int
    assessment: AclAssessmentResponse
    care_plan: CarePlanResponse
